### ISSUE TITLE
ImmPort crawler broken

### ISSUE THREAD

**Issue by zcqian** [biothings/biothings.crawler#8]
500 error from ES when running crawler.

```
2020-12-27 20:54:10 [elasticsearch] WARNING: PUT http://api.outbreak.info:9200/crawler_immport_covid_b45744c048c811eb8eecc81f66e68c96/_doc/https%3A%2
F%2Fwww.immport.org%2Fshared%2Fstudy%2FSDY1648 [status:500 request:0.074s]
2020-12-27 20:54:10 [scrapy.core.scraper] ERROR: Error processing {'Accession': 'SDY1648', 'Title': 'Sex differences in immune responses to SARS-CoV-
2 (Companion study to SDY1655)', 'DOI': '10.21430/M3ETFANV1O', 'Brief Description': 'In this study, we examined sex differences in viral loads, SARS-
CoV-2-specific antibody titers, plasma cytokines, as well as blood cell phenotyping in COVID-19 patients. ** THE DATA FOR THIS STUDY IS CONTAINED IN
SDY1655 **.'}
Traceback (most recent call last):
  File "/home/zqian/outbreak-resources-updater/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/zqian/outbreak-resources-updater/venv/lib/python3.6/site-packages/scrapy/utils/defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/home/zqian/outbreak-resources-updater/biothings.crawler/crawler/pipelines.py", line 47, in process_item
    res = indices.index(_index, _id, item)
  File "/home/zqian/outbreak-resources-updater/biothings.crawler/crawler/upload/__init__.py", line 269, in index
    return self.client.index(index=_index, id=_id, body=_source)
  File "/home/zqian/outbreak-resources-updater/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/zqian/outbreak-resources-updater/venv/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 396, in index
    body=body,
  File "/home/zqian/outbreak-resources-updater/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/home/zqian/outbreak-resources-updater/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/home/zqian/outbreak-resources-updater/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_reque
st
    self._raise_error(response.status, raw_data)
  File "/home/zqian/outbreak-resources-updater/venv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 301, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(500, 'exception', 'java.lang.IllegalArgumentException: java.lang.IllegalStateException: pipel
ine with id [resources-common] could not be loaded, caused by [ElasticsearchParseException[Error updating pipeline with id [resources-common]]; neste
d: ScriptException[compile error]; nested: IllegalArgumentException[Cannot cast null to a primitive type [void].];; ScriptException[compile error]; n
ested: IllegalArgumentException[Cannot cast null to a primitive type [void].];; java.lang.IllegalArgumentException: Cannot cast null to a primitive t
ype [void].]')
```

Seems related to the pipeline? But I don't remember using any pipeline/mapping for the crawlers. Will attempt to fix this tomorrow.

**Comment by zcqian** [comment]
This is a issue related to ES pipelines, not the crawler code.
